[build]
  command = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  
[build.caching]
  paths = ["node_modules", ".npm", ".venv", "venv", "python-packages"]
