[build]
  command = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18" # or the Node.js version your project needs
  PYTHON_VERSION = "3.8"

[build.caching]
  paths = ["node_modules", ".npm", ".venv", "venv", "python-packages"]
